### ISSUE TITLE
Info bar dissappears after unsuccessful geolocation

### ISSUE THREAD

**Issue by allisonmuise** [Esri/my-government-services#22]
Repro steps:
1. Collapse the info bar by clicking the arrow
2. Expand the info bar by clicking the arrow again
- Note that this works

1. Click geolocation button
2. Click OK when prompted that you are outside the service area
- Note that the info bar has collapsed and clicking the arrow does not expand it.

Workaround: Click the map to generate a route. The info bar expands and can once again be collapsed and expanded by clicking the arrow

**Comment by LindsayThomas** [comment]
This is expected behavior. Because there isn't a valid location the carousel will not display because it doesn't have any data to display.
