### ISSUE TITLE
App limited to browser locales that use a period as the decimal separator

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/my-government-services#24]
The app gets the distance from the address or click location to a point feature and then formats it for the locale, which converts it into a string.
carousel.js approximately line 1167:

```
if (mapPoint) {
    var dist = GetDistance(mapPoint, featureset[i].geometry);
    var distanceMiles = dojo.number.format(dist);
}
```

Later, it displays this distance in the infoPod by rounding it to the nearest 100th place.  The rounding requires the automatic conversion of the formatted distance string back into a number, and this fails if the decimal separator is not a period, which is the case for Canadian, Danish, Finnish, French, German, Italian, Norwegian, Spanish, and Swedish browser locales, among others (source: https://docs.oracle.com/cd/E19455-01/806-0169/overview-9/index.html).
Route.js approximately line 162:

```
//Round distance
function FormatDistance(dist, units) {
    var d = Math.round(dist * 100) / 100;
    if (d === 0) {
        return "";
    }
    return d + " " + units;
}
```

The result is a "NaN" display for the distance, e.g.,
![image](https://cloud.githubusercontent.com/assets/2125181/4980435/18e1cc12-6900-11e4-8729-34dc0ca5007a.png)

**Comment by LindsayThomas** [comment]
@MikeTschudi Was this reported by a customer?
