### ISSUE TITLE
My Location Button Not Working

### ISSUE THREAD

**Issue by mmclamb** [Esri/my-government-services#31]
I have deployed the My Government Services App and all seems well, except the My Location button is not working. If you select the button, the app just shows the loading GIF continuously. 

The app is currently running from a server within the DMZ. It is accessing GIS Services that are on another server behind the firewall. This public facing server acts as a reverse proxy to access those GIS Services. 

I placed the My Government Services app on the internal server where the GIS Services are running and the My Location button works as expected when run from that server. I have been working with Esri tech support and it was recommended that I post this issue here. Any help is greatly appreciated. The URL is below:

[http://gis.weho.org/GovernmentServices/]

**Comment by MikeTschudi** [comment]
Please restore the site's locator.js file.  At this point, it simply contains “This attachment was removed.”

Geolocation is failing because the GetExtent function provided by locator.js is missing.

**Comment by mmclamb** [comment]
I just replaced the locator.js file with the original file from the download, but it appears it still shows that same message. I have attached the locator.js file here for reference.

[locator.zip](https://github.com/Esri/my-government-services/files/174714/locator.zip)

**Comment by MikeTschudi** [comment]
Splendid.  Please clear the browser cache and try again.  The app is now working for me.

You can test that the updated file is being read by the browser by trying to access the file directly via its URL http://gis.weho.org/GovernmentServices/js/locator.js.

**Comment by mmclamb** [comment]
Ah - good call. Thanks for the help!

**Comment by MikeTschudi** [comment]
Glad to help.  That caching can be maddening!

**Comment by LindsayThomas** [comment]
@mmclamb @MikeTschudi  can we close this?

**Comment by mmclamb** [comment]
Yes – thank you!

Matthew McLamb
VP of GIS and Operations
Geographic Technologies Group
888.757.4222 ext. 171 toll free
919.223.8755 cell
