### ISSUE TITLE
MGS Application Web Browser Issue

### ISSUE THREAD

**Issue by kylesea** [Esri/my-government-services#32]
I have set up the My Government Services Application by following the steps on the [solutions ](http://solutions.arcgis.com/local-government/help/my-government-services/get-started/) webpage. The application works great on our internal web server in both IE and Chrome. When the app is placed on our external server it works great in IE but in Chrome there are service recall issues that make the application unstable. Below is a snip of the type of errors I receive within Chrome's developer window. The issue seems to only effect point web services that are in the application.  

![image](https://cloud.githubusercontent.com/assets/6886207/14742305/7795fc42-0869-11e6-865f-5510e3f5aef7.png)

Chrome Version: 49.0.2623.112 
IE Version: 11.0.9600.18282
Web Server: Windows Server  2008 R2

**Comment by MikeTschudi** [comment]
Kyle, thanks for the screenshot. When running the app, I see the data coming from the server, but the browser is blocking them from the app for security policy reasons.

I tried both http://webgis.altamonte.org/EsriMGS/ and https://webgis.altamonte.org/EsriMGS/, and the network errors I see are related to the mix of https and http (different errors for each) between the app and its services. I would double-check the consistency of protocol throughout the configuration, including in the proxy.config file.

If you set up the original download with the configured services, the protocols seem consistent, and you continue to see these security policy problems, please consider bringing this issue up with Esri Support. The MGS download is a supported app, and Support has significant expertise.

**Comment by kylesea** [comment]
Mike, Thanks for the input! I do have a case open with Support and we have been trying to work it out for the past week. I will pass along your feedback to the Support tech who is on the case.

**Comment by kylesea** [comment]
This issue was resolved by adding the following Action within the applications HTTP Response Headers:
![image](https://cloud.githubusercontent.com/assets/6886207/15329290/20fd088c-1c26-11e6-9bf1-b493e928d2c1.png)

With this addition there are no more issues running the application in Chrome or any other browser.
